services:
  hi-telos:
    build: .
    image: hi-telos:latest
    ports:
      - "8080:8080"
    environment:
      HI_APP_ROOT: /app
      HI_SERVER_BIND: 0.0.0.0:8080
    volumes:
      - type: bind
        source: ./config
        target: /app/config
        read_only: true
      - type: bind
        source: ./data
        target: /app/data
    restart: unless-stopped
